version: 0.0
os: linux
files:
  - source: <path-to-folder>/index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: <location-of-script-you-want-to-run>
      timeout: 300
      runas: root
    - location: <location-of-script-you-want-to-run>
      timeout: 300
      runas: root
  ApplicationStop:
    - location: <location-of-script-you-want-to-run>
      timeout: 300
      runas: root
