pipelines:
default:
- step:
name: Build
script:
- echo "Deploying to test environment"
artifacts:
- myapp.zip

- step:
name: Upload to S3
script:
# Test upload
- pipe: atlassian/aws-code-deploy:0.2.6
variables:
AWS_ACCESS_KEY_ID: 
AWS_SECRET_ACCESS_KEY:
AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
COMMAND: 'upload'
APPLICATION_NAME: ${APPLICATION_NAME}
S3_BUCKET: ${S3_BUCKET}
ZIP_FILE: 'myapp.zip'

- step:
name: Deploy with CodeDeploy
script:
# Test upload
- pipe: atlassian/aws-code-deploy:0.2.6
variables:
AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
COMMAND: 'deploy'
APPLICATION_NAME: ${APPLICATION_NAME}
DEPLOYMENT_GROUP: ${DEPLOYMENT_GROUP}
VERSION_LABEL: 'my-app-1.0.0'
IGNORE_APPLICATION_STOP_FAILURES: 'true'
FILE_EXISTS_BEHAVIOR: 'OVERWRITE'
WAIT: 'true'
